version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: voltagent-postgres
    environment:
      POSTGRES_DB: codegen_db
      POSTGRES_USER: codegen_user
      POSTGRES_PASSWORD: codegen_password
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/core/src/database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U codegen_user -d codegen_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: voltagent-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@voltagent.dev
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: unless-stopped
    profiles:
      - admin

volumes:
  postgres_data:
    driver: local

